# .github/workflows/convert-to-pdf.yml

name: MD to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'Chapter_01_Introduction/**.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: Chapter_01_Introduction
          output_dir: md
          build_html: false
      - uses: baileyjm02/markdown-to-pdf@v1
          with:
          input_dir: Chapter_02_Workflow
          output_dir: md
          build_html: false
      - uses: baileyjm02/markdown-to-pdf@v1
          with:
          input_dir: Chapter_03_Design_and_example_pick
          output_dir: md
          build_html: false
      - uses: baileyjm02/markdown-to-pdf@v1
          with:
          input_dir: Chapter_04_Openroad_first_run
          output_dir: md
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: mdtopdfs
          path: md
