# .github/workflows/convert-to-pdf.yml

name: MD to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    paths:
      - 'Chapter_00_Preparations/**.md'
      - 'Chapter_01_Introduction/**.md'
      - 'Chapter_02_Workflow/**.md'
      - 'Chapter_03_Design_and_example_pick/**.md'
      - 'Chapter_04_Openroad_first_run/**.md'
      - 'Chapter_05_PDK_Examination/**.md'
      - 'Chapter_06_Data_in_Openroad/**.md'
      - 'Chapter_07_LVS_and_DRC/**.md'
      - 'Chapter_08_Simulation_and_PPA/**.md'
      - 'Chapter_09_Scripting/**.md'
      - 'Chapter_10_GDS_and_Tapeout/**.md'
  workflow_dispatch:
    branches:
      - main

jobs:
  converttopdf:
    name: Build Course Summary PDF
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: create pdf folder
        id: pdf_folder
        run: |
          mkdir pdf

      - name: c00
        uses: docker://pandoc/extra:3.5
        with:
          args: >-
            --output=pdf/c00_preparations.pdf 
            --slide-level 2 
            --shift-heading-level=-1
            --listings
            --toc 
            --columns=50
            --template pandoc/templates/default_mod.latex
            --pdf-engine lualatex
            -t beamer 
            --from=markdown+rebase_relative_paths 
            Chapter_00_Preparations/c00_preparations.md 

      - name: c01_l
        uses: docker://pandoc/extra:3.5
        with:
          args: >-
            --output=pdf/c01_lecture.pdf 
            --slide-level 2 
            --shift-heading-level=-1 
            --toc 
            --columns=50
            --template pandoc/templates/default_mod.latex
            -t beamer 
            --from=markdown+rebase_relative_paths 
            Chapter_01_Introduction/c01_lecture.md 

      - name: c02_l
        uses: docker://pandoc/extra:3.5
        with:
          args: >-
            --output=pdf/c02_lecture.pdf 
            --slide-level 2 
            --shift-heading-level=-1 
            --toc 
            --columns=50 
            --template pandoc/templates/default_mod.latex
            -t beamer 
            --from=markdown+rebase_relative_paths 
            Chapter_02_Workflow/c02_lecture.md 

      - name: c03_l
        uses: docker://pandoc/extra:3.5
        with:
          args: >-
            --output=pdf/c03_lecture.pdf 
            --slide-level 2 
            --shift-heading-level=-1 
            --toc 
            --columns=50 
            --template pandoc/templates/default_mod.latex
            -t beamer 
            --from=markdown+rebase_relative_paths 
            Chapter_03_Design_and_example_pick/c03_lecture.md 

      - name: c04_l
        uses: docker://pandoc/extra:3.5
        with:
          args: >-
            --output=pdf/c04_lecture.pdf 
            --slide-level 2 
            --shift-heading-level=-1 
            --toc 
            --columns=50 
            --template pandoc/templates/default_mod.latex
            -t beamer 
            --from=markdown+rebase_relative_paths 
            Chapter_04_Openroad_first_run/c04_lecture.md 

      - name: c05_l
        uses: docker://pandoc/extra:3.5
        with:
          args: >-
            --output=pdf/c05_lecture.pdf 
            --slide-level 2 
            --shift-heading-level=-1 
            --toc 
            --columns=50 
            --template pandoc/templates/default_mod.latex
            -t beamer 
            --from=markdown+rebase_relative_paths 
            Chapter_05_PDK_Examination/c05_lecture.md 

      - name: c03_t
        uses: docker://pandoc/extra:3.5
        with:
          args: >-
            --output=pdf/c03_training.pdf 
            --slide-level 2 
            --shift-heading-level=-1 
            --toc 
            --columns=50 
            --template pandoc/templates/default_mod.latex
            -t beamer 
            --from=markdown+rebase_relative_paths 
            Chapter_03_Design_and_example_pick/c03_training.md 

      - name: c04_t
        uses: docker://pandoc/extra:3.5
        with:
          args: >-
            --output=pdf/c04_training.pdf 
            --slide-level 2 
            --shift-heading-level=-1 
            --toc 
            --columns=50 
            --template pandoc/templates/default_mod.latex
            -t beamer 
            --from=markdown+rebase_relative_paths 
            Chapter_04_Openroad_first_run/c04_training.md 

      - name: c05_t
        uses: docker://pandoc/extra:3.5
        with:
          args: >-
            --output=pdf/c05_training.pdf 
            --slide-level 2 
            --shift-heading-level=-1 
            --toc 
            --columns=50 
            --template pandoc/templates/default_mod.latex
            -t beamer 
            --from=markdown+rebase_relative_paths 
            Chapter_05_PDK_Examination/c05_training.md 

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: course_summary
          path: pdf

